insert into sign(id, name, video_url)
values (DEFAULT, 'Black', '/videos/black'),
       (DEFAULT, 'Good afternoon', '/videos/good_afternoon'),
       (DEFAULT, 'Pain', '/videos/pain'),
       (DEFAULT, 'Blue', '/videos/blue'),
       (DEFAULT, 'Happy', '/videos/happy'),
       (DEFAULT, 'Red', '/videos/red'),
       (DEFAULT, 'Bored', '/videos/bored'),
       (DEFAULT, 'Happy birthday', '/videos/happy_birthday'),
       (DEFAULT, 'Surprise', '/videos/surprise'),
       (DEFAULT, 'Can i help you', '/videos/can_i_help_you'),
       (DEFAULT, 'Hi', '/videos/hi'),
       (DEFAULT, 'Thank god', '/videos/thank_god'),
       (DEFAULT, 'Depressed', '/videos/depressed'),
       (DEFAULT, 'How are you', '/videos/how_are_you'),
       (DEFAULT, 'Where is the bathroom', '/videos/where_is_the_bathroom'),
       (DEFAULT, 'Exhausted', '/videos/exhausted'),
       (DEFAULT, 'Hungry', '/videos/hungry'),
       (DEFAULT, 'White', '/videos/white'),
       (DEFAULT, 'Frustrated', '/videos/frustrated'),
       (DEFAULT, 'No', '/videos/no'),
       (DEFAULT, 'Yes', '/videos/yes'),
       (DEFAULT, 'Good', '/videos/good'),
       (DEFAULT, 'Ok', '/videos/ok')